import { StyleSheet } from 'react-native';

export default styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    margin: 10,
  },
  RowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  NumberButton: {
    width: 80,
    margin: 5,
    height: 80,
    justifyContent: 'center',
    backgroundColor: 'white',
    border: '1px solid black',
    borderRadius: 35,
    boxShadow: '2px 2px 5px grey',
  },
  Button0: {
    width: 170,
    height: 80,
    margin: 10,
    justifyContent: 'center',
    backgroundColor: 'white',
    border: '1px solid black',
    borderRadius: 35,
    boxShadow: '2px 2px 5px grey',
  },
  OperatorButton: {
    width: 80,
    height: 80,
    margin: 5,
    justifyContent: 'center',
    border: '1px solid black',
    borderRadius: 35,
    boxShadow: '2px 2px 5px grey',
    backgroundColor: '#C0C0C0',
    color: '#FF9400',
  },
  ButtonEqual: {
    width: 60,
    height: 80,
    border: '1px solid black',
    borderRadius: 40,
    justifyContent: 'center',
    backgroundColor: '#FF9400',
    border: '1px solid black',
    borderRadius: 35,
    boxShadow: '2px 2px 5px grey',
    margin: 5,
  },
  ClearButton: {
    width: 300,
    height: 80,
    border: '1px solid black',
    borderRadius: 40,
    justifyContent: 'center',
    backgroundColor: '#C0C0C0',
    color: 'Black',
  },
  Result: {
    fontSize: 30,
    color: 'Black',
    marginBottom: 10,
  },
  Text: {
    fontSize: 30,
    color: 'Black',
    textAlign: 'center',
  },
  colorOrange: {
    color: '#FF9400',
  },
  colorWhite: {
    color: '#F5F5F5',
  },
});
